version: '3.4'

services:
  compentio.Ankara.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    expose:
      - "80"
    ports:
      - "8080:80"
      - "1443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  compentio.Ankara.database.init:
    environment:
      - ConnectionString="Data Source=XXX.XXX.XXX.X;Initial Catalog=ankara; Integrated Security=False; User Id=ankaraUser; Password=*******;"


  compentio.Ankara.database:
    environment:
     - SA_PASSWORD=*******
     - ACCEPT_EULA=Y
    ports:
      - "1433:1433"